<?php

/**
 * @file
 * Contains lexicon_search.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function lexicon_search_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the lexicon_search module.
    case 'help.page.lexicon_search':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function lexicon_search_theme() {
  return [
    'lexicon_search_results' => [
      'render element' => 'children',
    ],
  ];
}
